# Generated by Django 5.0 on 2024-12-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0005_auto_20241208_0257"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Report"),
                            ("weekly", "Weekly Report"),
                            ("monthly", "Monthly Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_transactions", models.IntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("successful_transactions", models.IntegerField(default=0)),
                ("failed_transactions", models.IntegerField(default=0)),
                ("refunded_transactions", models.IntegerField(default=0)),
                (
                    "average_transaction_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("report_data", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Payment Report",
                "verbose_name_plural": "Payment Reports",
                "ordering": ["-report_date"],
                "unique_together": {("report_date", "report_type")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("card", "Credit/Debit Card"),
                            ("bank", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_details", models.JSONField(blank=True, default=dict)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_id"], name="payment_tra_transac_143f1c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payment_tra_status_373de7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payment_tra_created_0d0f1d_idx"
                    ),
                ],
            },
        ),
    ]
