# Generated by Django 5.0 on 2024-12-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreport",
            name="net_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentreport",
            name="total_loss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentreport",
            name="total_profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
