# Generated by Django 5.0 on 2024-12-07 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_discount_order_notes_order_shipping_cost_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_status_c6dd84_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_cost",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="stripe_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tracking_number",
        ),
    ]
